# Netlify Configuration for B.A.T.S. Tool

[build]
  # No build command needed for static site
  publish = "."
  functions = "netlify/functions"

# Redirect rules
[[redirects]]
  # Force HTTPS
  from = "http://batstool.com/*"
  to = "https://batstool.com/:splat"
  status = 301
  force = true

[[redirects]]
  # Redirect www to non-www
  from = "https://www.batstool.com/*"
  to = "https://batstool.com/:splat"
  status = 301
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    
    # HSTS (only enable after SSL is working)
    # Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Content Security Policy
    Content-Security-Policy = '''
      default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      font-src 'self' data:;
      connect-src 'self' https://api.etherscan.io https://api.bscscan.com https://api.polygonscan.com https://api.blockcypher.com https://blockchain.info https://api.blockchair.com https://*.infura.io https://mempool.space https://api.mainnet-beta.solana.com https://rpc.ankr.com https://solana-mainnet.g.alchemy.com https://api.arkhamintelligence.com https://api.trongrid.io https://tronscan.org https://api.blockchain.info https://walletexplorer.com https://www.walletexplorer.com https://*.solscan.io https://pro-api.solscan.io https://public-api.solscan.io https://api.solscan.io https://api.xrpscan.com https://xrplcluster.com https://s1.ripple.com https://fullnode.mainnet.sui.io https://sui-mainnet.blockvision.org https://rpc-mainnet.suiscan.xyz https://suiscan.xyz https://midgard.ninerealms.com https://midgard.thorchain.info https://viewblock.io https://api.bridgers.xyz https://images.bridgers.xyz https://scan.layerzero-api.com https://layerzeroscan.com https://layerzero.network https://stargate.finance https://api.stargate.finance https://api.wormholescan.io https://wormholescan.io https://wormhole.com https://portalbridge.com https://api.synapseprotocol.com https://synapseprotocol.com https://synapsebridge.com;
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self';
    '''

# Cache control
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# SPA fallback (not needed for this app, but included for reference)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200